# Site settings
title: colethecoder
email: mail@colethecoder.com
copyright_name: Tom Cole
description: "C#, Functional Programming, Cloud, SRE etc..."
baseurl: ""
url: "http://colethecoder.com"
twitter_username: colethecoder
github_username:  colethecoder
email_username:  mail@colethecoder.com
linkedin_username: colethecoder

# Build settings
plugins: [jekyll-paginate, jekyll-feed]
markdown: kramdown
permalink: pretty
paginate: 5
root_url: "http://colethecoder.com"
highlighter: rouge